# fly.toml app configuration file generated for apimanyfaces on 2024-02-16T07:35:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apimanyfaces'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
