//Dependencies
const mongoose = require('mongoose')

const itemSchema = new mongoose.Schema({
    name: {
        type: String,
        enum: [
            'Backpack',
            'Bedroll',
            'Bell',
            'Blanket',
            'Block and Tackle',
            'Caltrops',
            'Candle',
            'Canvas',
            'Chalk',
            'Climbing Kit',
            'Fishing Hook',
            'Fishnet',
            'Flask',
            'Flint and Steel',
            'Grappling Hook',
            'Hammer',
            'Healer’s Tools',
            'Holy Water',
            'Lantern',
            'Mirror',
            'Mug',
            'Parchment',
            'Piton',
            'Pole',
            'Pot',
            'Pouch',
            'Rations',
            'Robes',
            'Rope',
            'Sack',
            'Sledge',
            'Spellbook',
            'Spikes',
            'Spyglass',
            'Tent',
            'Torch',
            'Vial',
            'Waterskin',
            'Whetstone',
            'Dagger',
            'Shortsword',
            'Longsword',
            'Greatsword',
            'Shortbow',
            'Longbow',
            'Crossbow',
            'Arrows',
            'Quiver',
            'Leather Armor',
            'Chain Shirt',
            'Breastplate',
            'Scale Mail',
            'Half Plate',
            'Full Plate',
            'Buckler',
            'Tower Shield',
        ],
        default: 'Backpack',
    },
    description: {
        type: String,
    }
})
module.exports = itemSchema